/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author Phong Thinh
 */
public class MainFramee extends javax.swing.JFrame {

    public MainFramee() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Hệ thống Quản lý Tiệm Giặt Ủi ");
    }

    // Các method xử lý sự kiện MENU
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuItemKhachHang = new javax.swing.JMenuItem();
        menuItemDichVu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemDonHang = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemThongKe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HỆ THỐNG QUẢN LÝ TIỆM GIẶT ỦI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );

        jMenu3.setText("Quản lý danh mục");

        menuItemKhachHang.setText("Khách Hàng");
        menuItemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKhachHangActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemKhachHang);

        menuItemDichVu.setText("Dịch vụ");
        menuItemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDichVuActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemDichVu);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Quản lý đơn hàng");

        menuItemDonHang.setText("Đơn hàng");
        menuItemDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDonHangActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemDonHang);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Thống Kê");

        menuItemThongKe.setText("Doanh thu");
        menuItemThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThongKeActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemThongKe);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKhachHangActionPerformed
        // TODO add your handling code here:
        KhachHangGUI khachHangGUI = new KhachHangGUI();
        khachHangGUI.setVisible(true);
        khachHangGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemKhachHangActionPerformed

    private void menuItemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDichVuActionPerformed
        // TODO add your handling code here:
        DichVuGUI dichVuGUI = new DichVuGUI();
        dichVuGUI.setVisible(true);
        dichVuGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemDichVuActionPerformed

    private void menuItemDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDonHangActionPerformed
        // TODO add your handling code here:
        DonHangGUI donHangGUI = new DonHangGUI();
        donHangGUI.setVisible(true);
        donHangGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemDonHangActionPerformed

    private void menuItemThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThongKeActionPerformed
        // TODO add your handling code here:
        ThongKeGUI thongKeGUI = new ThongKeGUI();
        thongKeGUI.setVisible(true);
        thongKeGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuItemThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFramee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFramee().setVisible(true);
            }
        });
    }
    // Xử lý menu Quản lý -> Khách hàng


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuItemDichVu;
    private javax.swing.JMenuItem menuItemDonHang;
    private javax.swing.JMenuItem menuItemKhachHang;
    private javax.swing.JMenuItem menuItemThongKe;
    // End of variables declaration//GEN-END:variables
}
