/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import dao.ThongKeDAO;
//import javax.swing.table.DefaultTableModel;
//import java.util.Date;
//import java.util.Map;

/**
 *
 * @author Phong Thinh
 */
public class ThongKeGUI extends javax.swing.JFrame {

//    private ThongKeDAO thongKeDAO = new ThongKeDAO();
//    private DefaultTableModel tableModel;
//
//    public ThongKeGUI() {
//        initComponents();
//        setLocationRelativeTo(null);
//        setTitle("Thống Kê Doanh Thu - Tiệm Giặt Ủi");
//        initTable();
//        loadThongKeTongQuan();
//    }
//
//    private void initTable() {
//        tableModel = (DefaultTableModel) tableThongKe.getModel();
//        tableModel.setColumnIdentifiers(new String[]{
//            "STT", "Chỉ tiêu", "Giá trị"
//        });
//    }
//
//    private void loadThongKeTongQuan() {
//        tableModel.setRowCount(0);
//
//        Map<String, Object> thongKe = thongKeDAO.thongKeTongQuan();
//
//        // Thêm dữ liệu vào table
//        tableModel.addRow(new Object[]{"1", "Tổng doanh thu",
//            String.format("%,d VNĐ", ((Double) thongKe.get("tongDoanhThu")).intValue())});
//        tableModel.addRow(new Object[]{"2", "Tổng số đơn hàng", thongKe.get("tongDonHang")});
//        tableModel.addRow(new Object[]{"3", "Đơn mới", thongKe.get("donMoi")});
//        tableModel.addRow(new Object[]{"4", "Đang xử lý", thongKe.get("donDangXuLy")});
//        tableModel.addRow(new Object[]{"5", "Đơn hoàn thành", thongKe.get("donHoanThanh")});
//        tableModel.addRow(new Object[]{"6", "Đơn đã hủy", thongKe.get("donDaHuy")});
//        tableModel.addRow(new Object[]{"7", "Tỷ lệ hoàn thành",
//            String.format("%.1f%%", thongKe.get("tyLeHoanThanh"))});
//
//        // Doanh thu hôm nay
//        double doanhThuHomNay = thongKeDAO.thongKeDoanhThuTheoNgay(new Date());
//        tableModel.addRow(new Object[]{"8", "Doanh thu hôm nay",
//            String.format("%,d VNĐ", (int) doanhThuHomNay)});
//
//        // Doanh thu tuần này
//        double doanhThuTuan = thongKeDAO.thongKeDoanhThuTuanHienTai();
//        tableModel.addRow(new Object[]{"9", "Doanh thu tuần này",
//            String.format("%,d VNĐ", (int) doanhThuTuan)});
//
//        // Doanh thu tháng này
//        double doanhThuThang = thongKeDAO.thongKeDoanhThuThangHienTai();
//        tableModel.addRow(new Object[]{"10", "Doanh thu tháng này",
//            String.format("%,d VNĐ", (int) doanhThuThang)});
//    }
//
//    private void loadThongKeDichVu() {
//        tableModel.setRowCount(0);
//        tableModel.setColumnIdentifiers(new String[]{"STT", "Tên dịch vụ", "Số lượng bán"});
//
//        Map<String, Integer> dichVuBanChay = thongKeDAO.thongKeDichVuBanChay();
//        int stt = 1;
//
//        for (Map.Entry<String, Integer> entry : dichVuBanChay.entrySet()) {
//            tableModel.addRow(new Object[]{stt++, entry.getKey(), entry.getValue()});
//        }
//    }
//
//    private void loadThongKeKhachHang() {
//        tableModel.setRowCount(0);
//        tableModel.setColumnIdentifiers(new String[]{"STT", "Khách hàng", "Số đơn"});
//
//        Map<String, Integer> khachHangThanThiet = thongKeDAO.thongKeKhachHangThanThiet();
//        int stt = 1;
//
//        for (Map.Entry<String, Integer> entry : khachHangThanThiet.entrySet()) {
//            tableModel.addRow(new Object[]{stt++, entry.getKey(), entry.getValue()});
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
